### ISSUE TITLE
A new method to reorder codec preference in SDP m=video lines

### ISSUE THREAD

**Issue by warrenjmcdonald** [rtc-io/rtc-sdp#2]
Could a new method be implemented for reordering the codec preferences in SDP m=video lines

This is pretty simple other than assumptions about the numbers to reorder. They are static in Chrome, but I am unsure about other browsers. 

Chrome uses 
m=video 9 UDP/TLS/RTP/SAVPF 100 101 107 116 117 96 97 99 98
.
.
a=rtpmap:100 VP8/90000 
a=rtpmap:101 VP9/90000 
a=rtpmap:107 H264/90000

To be browser independent we would need to parse all the rtpmap lines to first map the codec numbers to the codec strings, before reordering the numbers in the m-video line. 

The method should accept an ordered list of codec strings. Whilst we may end up with many available codecs overtime, I would not envisage any more than 3 ever being specified as preferences.  

The browser must already be offering the codec, it is just the order we want to change. So if there is no rtpmap for a codec string specified then it will be ignored and removed from preference set

If a single codec string is specified, it's mapped number should be moved to the first (most left) position. 
If more than 1  codec is specified, the first's number should be moved to first codec position, and the second to second, third to third.

Any existing codec numbers (not in the set derived from the codec strings) should survive, and be placed to the right of the preferred set.

**Comment by silviapfeiffer** [comment]
This is totally possible with this framework. All you need to implement is a function similar to this: https://github.com/rtc-io/rtc-sdp/blob/master/constrain-bandwidth.js which takes the SDP and munges it into shape.

Then hand on the munged SDP as an sdpfilter function to your quickconnect object as is demonstrated here: https://github.com/rtc-io/rtc-sdp/blob/master/examples/constrain-bandwidth.js .

You can either implement the codec-munging function privately, or if you'd like to contribute it here, that would be great also.

**Comment by nathanoehlman** [comment]
Hi @warrenjmcdonald,

I've just implemented this functionality in https://github.com/rtc-io/rtc-sdp/pull/3.

If you could take a look and check to see whether that looks like it fulfils this use case, that'd be appreciated.

Cheers,
Nathan

**Comment by warrenjmcdonald** [comment]
Thanks - It looks like it will do what we (and others) will need. I am not the best JS person, so I would need to get @magestican to have a look as well.

**Comment by magestican** [comment]
> One thought though is it worth grouping the filters in a separate filters directory?
> 
> This way usage would look something like:
> 
> const quickconnect = require('rtc-quickconnect');
> const preferCodecs = require('rtc-quickconnect/filters/prefer-codecs');
> That way you can start to add more filters without cluttering up the root directory. Up to you though :) 

@DamonOehlman this looks nice but its not dynamic at least not in our solution since we browserify quickconnect and publish the bundle for our apps, i think the current implementation is good

**Comment by nathanoehlman** [comment]
Closed with #3 - published as `1.3.0`
